### ISSUE TITLE
Where is the list of endpoints supported by the LZA? RDS is missing from the example?

### ISSUE THREAD

**Issue by roncanepa** [awslabs/landing-zone-accelerator-on-aws#114]
**Is your feature request related to a problem? Please describe.**
I'm reviewing the list of centralized endpoints in our new landing zone and making sure to enable the ones we'll want/need.  I noticed that RDS is missing from the list of commented-out endpoints.  We got our initial config from Proserv, which had a long list of endpoints commented out that matches very closely with the example from this repo: [network-config.yaml](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/reference/sample-configurations/aws-best-practices/network-config.yaml#L526)

Does RDS being missing mean it's not supported? Is it just an oversight?  Where do I find the list of supported services, and, more importantly, the config value (service name slug, etc) I'm supposed to use for any service not already listed in the file?  Related: #84 

**Describe the feature you'd like**
I somehow need an authoritative list of AWS service endpoints supported by the LZA. If the commented list in the network file IS the list, please explicitly state so.

**Additional context**

**Comment by awsclemj** [comment]
Hello @roncanepa, and thanks for reaching out to the LZA team!

Due to the frequently evolving nature of interface endpoints, we do not keep an active list of supported endpoints in our sample config or source code. Theoretically, the engine can support any service endpoint that is documented [here](https://docs.aws.amazon.com/vpc/latest/privatelink/aws-services-privatelink-support.html). The service name that should be input into the configuration file is the suffix after `com.amazonaws.region`. 

One thing to note is there is not always regional parity of features for interface endpoints, namely endpoint policies. Presently, our engine assumes that endpoint policies are supported on all endpoints with the exception of the [following services](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/accelerator/lib/stacks/network-vpc-endpoints-stack.ts#L689). We welcome any enhancement requests if this list changes/needs modification.

I hope that information is helpful! We appreciate your feedback regarding the documentation, and we are working to improve our config API reference in forthcoming releases. Please let us know if there's anything more I can do to help here.

**Comment by roncanepa** [comment]
Thank you for all your help, @awsclemj , I appreciate it.  This is good enough to help me out for now.
