### ISSUE TITLE
Build fails with "Invalid value undefined"

### ISSUE THREAD

**Issue by jacekhewko** [awslabs/landing-zone-accelerator-on-aws#129]
**Describe the bug**
We've just deployed brand new AWS Landing Zone Accelerator and wanted to deploy hybrid networking solution based on the workshop studio instructions: https://catalog.workshops.aws/landing-zone-accelerator/en-US/lza-administrators/network-configuration

Unfortunately, when releasing a change on the AWSAccelerator-Pipeline - it fails on the Build step. At first, the error was:

```

[Container] 2023/04/13 13:09:37 Running command yarn validate-config $CODEBUILD_SRC_DIR_Config
--
817 | yarn run v1.22.19
818 | $ ts-node $PWD/packages/@aws-accelerator/accelerator/lib/config-validator.ts /codebuild/output/src965/src/s3/01
819 | 2023-04-13 13:09:40.435 \| info \| config-validator \| Config source directory -  /codebuild/output/src965/src/s3/01
820 | 2023-04-13 13:09:40.448 \| info \| iam-config-validator \| iam-config.yaml file validation started
821 | 2023-04-13 13:09:40.472 \| warn \| config-validator \| Config file validation failed !!!
822 | 2023-04-13 13:09:40.473 \| warn \| config-validator \| Error: Could not parse content:
823 | * Invalid value undefined supplied to /vpcs/5/account
824 | * Invalid value undefined supplied to /vpcFlowLogs in iam-config.yaml config file
825 | 2023-04-13 13:09:40.473 \| warn \| config-validator \| Error: Could not parse content:
826 | * Invalid value undefined supplied to /vpcs/5/account
827 | * Invalid value undefined supplied to /vpcFlowLogs in network-config.yaml config file
828 | error Command failed with exit code 1.
829 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
830 |  
831 | [Container] 2023/04/13 13:09:40 Command did not exit successfully yarn validate-config $CODEBUILD_SRC_DIR_Config exit status 1
832 | [Container] 2023/04/13 13:09:40 Phase complete: BUILD State: FAILED
833 | [Container] 2023/04/13 13:09:40 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: yarn validate-config $CODEBUILD_SRC_DIR_Config. Reason: exit status 1

```

So what I tried is removing the `vpcFlowLogs` completely from the network-config.yaml, and as it didn't help, I re-added it again. But this time the error changed for:

```

2023-04-13 14:27:17.376 \| info \| iam-config-validator \| iam-config.yaml file validation started
--
821 | 2023-04-13 14:27:17.397 \| warn \| config-validator \| Config file validation failed !!!
822 | 2023-04-13 14:27:17.397 \| warn \| config-validator \| Error: Could not parse content:
823 | * Invalid value undefined supplied to /vpcs/5/account in iam-config.yaml config file
824 | 2023-04-13 14:27:17.397 \| warn \| config-validator \| Error: Could not parse content:
825 | * Invalid value undefined supplied to /vpcs/5/account in network-config.yaml config file
826 | error Command failed with exit code 1.

```

So now I removed all the VPCs declared in 'vpcs' to see if this helps, but again:

```

2023-04-14 09:38:45.201 \| info \| iam-config-validator \| iam-config.yaml file validation started
--
821 | 2023-04-14 09:38:45.216 \| warn \| config-validator \| Config file validation failed !!!
822 | 2023-04-14 09:38:45.216 \| warn \| config-validator \| Error: Could not parse content:
823 | * Invalid value undefined supplied to /vpcs in iam-config.yaml config file
824 | 2023-04-14 09:38:45.216 \| warn \| config-validator \| Error: Could not parse content:
825 | * Invalid value undefined supplied to /vpcs in network-config.yaml config file
826 | error Command failed with exit code 1.

```

What is interesting, `iam-config.yaml` was never modified so no idea why would it fail if I only modified networking configuration based on the Worhskop Studio instructions.

Similar errors happened when we tried to change the `security-config.yaml` according to best practices repo, but then we decided to revert back to default file contents and focus on networking first.

Is there anything that needs to be added on top of the Workshop documentation in order to get this work, or it's a bug?

**To Reproduce**
Follow all the network configuration steps advised in the AWS Workshop Studio and then try to release your changes in AWS Pipeline:
https://catalog.workshops.aws/landing-zone-accelerator/en-US/lza-administrators/network-configuration

**Expected behavior**
Pipeline should succeed on all its steps

- [ ] Version: release/v1.3.2

- [ ] Region:
eu-west-2

- [ ] Was the solution modified from the version published on this repository?
No

- [x] Were there any errors in the CloudWatch Logs?
Nothing more than described above

Any help is much apprieciated as this is quite important for the project.
Thanks.

**Comment by erwaxler** [comment]
Hi @jacekhewko , thank you for your interest in the Landing Zone Accelerator!

I agree that the validator should not identify other files (`iam-config.yaml` in your case), I have added this bug to our roadmap to be addressed.

Regarding the validation issue you encountered, I would encourage you to use the LZA [TypeDocs](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.NetworkConfig.html) to verify the required properties across the LZA configuration files.  

Addressing your issues chronologically:

Initially, your config file was determined to be invalid for two reasons:
```
823 | * Invalid value undefined supplied to /vpcs/5/account
824 | * Invalid value undefined supplied to /vpcFlowLogs
```

Line 823 indicates you have 5 VPC's defined, and the 5th VPC has an invalid value provided for the `account`. Please see [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.VpcConfig.html) for an example of a defined VPC with the account property included.

Line 824 indicates your value for vpcFlowLogs is invalid. This is because vpcFlowLogs is a required parameter by LZA. We currently have an open [issue](https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/96) to make them optional, but for now the validation is correct in indicating they are required for the LZA to run.

VPCs are also a required property, so if you wished to deploy zero VPCs you would define it in your `network-config.yaml` file like so:
```
vps: []
```

**Comment by roncanepa** [comment]
[Note: I'm not affiliated with AWS]  What I've found helpful as well is to use the "local synth" capability of the cdk to test my config files before firing off the pipeline.  It doesn't catch everything but it certainly helps, especially since it can run in under a minute versus the 30-45 minutes of an LZA pipeline run.

Look at the "Do a dry run of the LZA engine" section.  Note that you'll need to set up your CLI access with appropriate credentials, as the synth pulls info from your environment. If you don't have this or don't have your creds refreshed, it'll just hang.

https://catalog.workshops.aws/landing-zone-accelerator/en-US/lza-optional/working-with-environment/validate-lza-repos

**Comment by awsclemj** [comment]
Hello,

v1.4.0 of the solution fixes both of the issues captured in this ticket. VPC flow logs [are now optional](https://github.com/awslabs/landing-zone-accelerator-on-aws/commit/e53a02cecb3c54a51bc96be45ee1d87e6a0c1b73), and the config validator no longer produces [duplicate errors](https://github.com/awslabs/landing-zone-accelerator-on-aws/commit/e2f8f2b72e1e94ac62cb702fadb57f25e6c9d2d2).

I will be closing out this issue. Thank you for your feedback!
