### ISSUE TITLE
Comparison to ASEA and plan to build same capabilities

### ISSUE THREAD

**Issue by rverma-dev** [awslabs/landing-zone-accelerator-on-aws#144]
While it is mentioned that ASEA is now entering maintenance mode and all new installations are preferred through LZA, there are a few limitations here
1. ASEA provide running the account bootstrap flow incrementally i.e. only the new account has stack provisioning. Is there any similar functionality here?
2. ASEA provide running multiple new accounts flow concurrently, i.e. 10 concurrent step functions can be invoked to provision 10 new accounts
3. ASEA provide auto-assigning vpc networks from a larger network range, e.g. provided we have declared 10.0/8 network, we can continuously provision new VPC by just providing the cidr block size and ASEA will automatically provide the next unallocated cidr range, allocated ranges are stored in dynamodb.

**Comment by awsclemj** [comment]
Hello, and thank you for reaching out to the LZA team! I'll be happy to address your questions/comments. However firstly, I would like to assure you that the LZA team is doing its due diligence in working directly with the team behind ASEA to ensure we are meeting ASEA customers' needs. Now, to answer your questions directly:

1. With v1.4.0 of our solution onward, we offer this functionality so bootstrapping only occurs on new accounts or if an update of the bootstrap stack is required. We have already received positive feedback that this significantly speeds up pipeline runs.
2. We support concurrent account creation both in AWS Organizations-only deployments and AWS Control Tower-based deployments. Note: concurrent account provisioning in Control Tower environments is 5 due to their [service quotas](https://docs.aws.amazon.com/controltower/latest/userguide/limits.html).
3. LZA provides native VPC IPAM functionality and allows you to provision VPCs in a similar manner using an AWS-managed service rather than a custom resource. More information on VPC IPAM can be found [here](https://docs.aws.amazon.com/vpc/latest/ipam/what-it-is-ipam.html)

I hope this information is helpful! Please feel free to write us back if you have any follow-up questions.
