### ISSUE TITLE
Enabling hardware MFA via config possible?

### ISSUE THREAD

**Issue by dnz-bdeboer** [awslabs/landing-zone-accelerator-on-aws#160]
In the IAM identity centre I can enable hardware security keys, but couldn't find a setting to specify this in the accelerator config. Is it correct I have to take this step manually and cannot provide that in config (yet)?

**Comment by awsclemj** [comment]
Hello @dnz-bdeboer, and thank you for reaching out to the LZA team!

It is not possible to enable hardware security keys via API, so doing so using LZA is also not possible. You can follow [this documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable.html) in order to configure your hardware security keys based on type of key you'd like to use.

I hope this was helpful! I will be closing this issue, but please feel free to follow-up or open new issues as you have additional questions. Thank you for your interest in Landing Zone Accelerator!
