### ISSUE TITLE
How do I reach internet from Workload account using Hub and Spoke VPC?

### ISSUE THREAD

**Issue by jacekhewko** [awslabs/landing-zone-accelerator-on-aws#164]
Hi,

We've deployed Advanced Networking Configuration from the workshop studio: https://catalog.workshops.aws/landing-zone-accelerator/en-US/lza-administrators/network-configuration/advanced-network-setup

And now I'm trying to test it out by creating EC2 instance with Public IP in my Workload account under Hub and Spoke VPC.

Unfortunately, I can't get internet access neither from `Hub-and-Spoke-A` or `Hub-and-SpokeTgwAttach-A` subnets.

What I'm trying to do is either successfully SSH into the EC2 instance or just see it's resolving in the browser using its Public IP.

What am I missing here?

Thanks in advance

PS. Isnt the Hub-and-Spoke -> Core-Network target gateway missing the routetables?

<img width="972" alt="image" src="https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/50452852/870a6052-6e8a-4e03-ae42-5cb115eedbbd">

**Comment by awsclemj** [comment]
Hello @jacekhewko, and thanks for reaching the Landing Zone Accelerator on AWS team!

If you're following the Immersion Day guide to set up your network, that guide does not have any steps for enabling ingress routing. What the guide does offer is a means to set up centralized egress, which is configured in the [core network](https://catalog.workshops.aws/landing-zone-accelerator/en-US/lza-administrators/network-configuration/advanced-network-setup/core-network) section. This configuration should be applied along with the hub and spoke configuration if it hasn't been already.

Once this configuration has been applied, you should be able to connect to your instances via Systems Manager Session Manager since that service only requires outbound Internet connectivity. Ingress connectivity would require further customization that is beyond the scope of the Immersion Day guide. 

I hope this helps! Thank you for your interest in the solution.
