### ISSUE TITLE
Session Manager settings clobbers existing configuration

### ISSUE THREAD

**Issue by tdmalone** [awslabs/landing-zone-accelerator-on-aws#29]
**Describe the bug**
When LZA is installed in existing accounts that already contain custom Session Manager settings, the custom resource (https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/source/packages/%40aws-accelerator/constructs/lib/aws-ssm/session-manager-settings/index.ts) used to create the `SSM-SessionManagerRunShell` document doesn't fail if the document already exists; it instead adopts the document into management and clobbers the existing settings.

To avoid breaking existing workloads, this custom resource should ideally fail if the document already exists, rather than implicitly importing and replacing it (or potentially the built-in `AWS::SSM::Document` resource could be used instead?)

**To Reproduce**
Install LZA into existing accounts that have custom Session Manager settings.

**Expected behavior**
- Session Manager settings to be applied to accounts that don't already have custom settings
- CloudFormation stack to error when settings already exist, so that an informed decision can be made about whether to remove the existing settings

**Please complete the following information about the solution:**

- [x] Version: 1.2.2
- [x] Region: ap-southeast-2
- [ ] Was the solution modified from the version published on this repository? unknown
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? n/a
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? n/a
- [ ] Were there any errors in the CloudWatch Logs? n/a

**Screenshots**
n/a

**Additional context**
n/a

**Comment by rgd11** [comment]
Hello @tdmalone , thank you for filing an issue with the Landing Zone Accelerator team!

Currently, this is an expected behavior within LZA as we are applying the defined state within the configuration to the imported account. Additionally, you can [exclude](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.SessionManagerConfig.html) the specific accounts and regions to avoid LZA taking action on the imported account.

Closing this issue, please reopen if you have additional questions.
