### ISSUE TITLE
bug(cicd): Change to config repo does not trigger the AWSAccelerator-Pipeline

### ISSUE THREAD

**Issue by flochaz** [awslabs/landing-zone-accelerator-on-aws#35]
**Describe the bug**
For any change to be deploy after a commit pushed to the `aws-accelerator-config` codecommit repo I have to click on "Release Change"  in console for them to be applied.

**To Reproduce**
Push updates to the config repo. Nothing will happen in pipeline

**Expected behavior**
Automatic trigger of `AWSAccelerator-Pipeline` on `aws-accelerator-config` codecommit repo commits.

**Please complete the following information about the solution:**

- [x] Version: v1.3.0

- [x] Region: eu-west-1
- [x] Was the solution modified from the version published on this repository? No
- [x] If the answer to the previous question was yes, are the changes available on GitHub? -
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses? Yes
- [x] Were there any errors in the CloudWatch Logs? No

**Comment by rycerrat** [comment]
Hi @flochaz!

Hope you're doing well.

Thank you for submitting an issue for the LZA. At the moment this is the desired configuration, as many customers prefer to make several, small changes to their configuration repo before triggering the pipeline. Due to the broad permission set which the LZA pipeline has to modify any and all resources across an AWS Organization, the triggering of the pipeline should be a deliberate action.

I think there is a valid argument to make a configurable parameter to automatically trigger the pipeline after new commits, however that may not outweigh the risk of customers unintentionally triggering their LZA pipeline and deploying undesired changes.

If you would like to enable this behavior, you can manually update the Code Pipeline in the AWS Code Pipeline console by doing the following:

- Go to the Accelerator Pipeline (not installer).
- Edit the Pipeline
- Edit the Source stage of the Pipeline
- For the Configuration Action Group, point to the proper Code Commit Repo/branch and select 'Done'

I have also included a link to the documentation here:
https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html

Since this is currently our intended behavior, I'll go ahead and resolve this issue. Please reach out if you have any further questions or concerns. 

Cheers!
