### ISSUE TITLE
getting email for Node.js 16 "AWS Lambda end of support for Node.js 16" for Lambda functions which are deployed using LZA 1.4.3

### ISSUE THREAD

**Issue by rupeshdumbre2021** [awslabs/landing-zone-accelerator-on-aws#363]
Today we have received emails for each account where we are using LZA 1.4.3 and all states that we need to upgrade existing Node.js 16 function to Node.js 20 before June 20,2024.

Can someone confirm this is taken care in latest release of LZA 1.5.2. or do we have to wait for next release of LZA for its resolution.

**Comment by robertcurcio** [comment]
https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/362

**Comment by johnraws** [comment]
@rupeshdumbre2021 Thank you for opening this issue regarding the upcoming Node16 EOL in June of 2024. The fix for this will be tracked as part of #362. 

To directly answer your question, v1.5.2 has many of the Lambda functions upgraded to Node18, but there are still some functions utilizing the Node16 runtime and need to be updated. 

This issue will be closed in favor of #362
