### ISSUE TITLE
Improve Log Archive account documentation

### ISSUE THREAD

**Issue by tombart** [awslabs/landing-zone-accelerator-on-aws#374]
**Is your feature request related to a problem? Please describe.**
The docs for Log Archive account are quite light, there is no explanation on how encryption happens, what keys are used or how to decrypt logs once landed in Log Archive account. I'm specifically targeting aws-accelerator-central-logs bucket where all logs there are encrypted. 

**Describe the feature you'd like**
A clear documentation explaining how encryption works and how to decrypt those logs for further processing.

**Comment by bo1984** [comment]
Hi Tomasz! Thank you for using the Landing Zone Accelerator on AWS (LZA) solution. We include details around the architecture of the LZA solution, including the centralized logging portion and which KMS Keys are used for encrypting the objects at rest. Please reference the Implementation Guide for [documentation](https://docs.aws.amazon.com/pdfs/solutions/latest/landing-zone-accelerator-on-aws/landing-zone-accelerator-on-aws.pdf#architecture-diagram). If you have any other questions around the logging architecture, please do not hesitate to ask.

**Comment by erikvdijk88** [comment]
> Hi, found the issue, the files in the bucket are actually gzipped but are dropped there by the stream without '.gz' extension. Would it be possible to add .gz extension to those files? was it done intentionally?

Thank you for this mention! was very easy thing I did not see but finally I can view the logs

**Comment by joshuahigginson1** [comment]
Hi Team, just jumping on this thread - is it possible to enable S3 Bucket Keys for all of the central logging buckets?

**Comment by erwaxler** [comment]
Hi @tombart , I believe the original issue has been fixed in v1.11.0 of the Landing Zone Accelerator which was released today.  You can now define a `firehoseLogExtension` to specify the file extension for files delivered to the bucket:

https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/interfaces/___packages__aws_accelerator_constructs_lib_aws_firehose_cloudwatch_to_s3_firehose.CloudWatchToS3FirehoseProps.html#firehoseLogExtension

I will go ahead and close this issue, for new feature requests or bugs please create a new GitHub issue. Thanks for your support of the Landing Zone Accelerator!
