### ISSUE TITLE
SCP deletion on finalize stage

### ISSUE THREAD

**Issue by alexhaycock** [awslabs/landing-zone-accelerator-on-aws#441]
**Describe the bug**
In two instances of LZA that we have deployed in the past we have seen an issue where the SCP's are deleted in the Finalize stage of the pipeline. After the Accounts stage they are there and can be seen but as soon as the finalize stage completes the policies are deleted. 

The Finalize stack seems to go from **UPDATE_COMPLETE** to **UPDATE_COMPLETE_CLEANUP_IN_PROGRESS** as shown in the screenshots then starts deleting the SCP attachments and policies.

**To Reproduce**
We're not sure on what causes this issue we've deployed a few LZA's and its only happened on two of them.

**Expected behavior**
After the pipeline has run the SCP policies to be showing in AWS organizations and the SCP's are applied to the configured OU's. 

**Please complete the following information about the solution:**

- [ ] Version: v.1.6.0
- [ ] Region: eu-west-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? Please see the screenshots.

**Screenshots**
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/93584021/43890887-9b72-4b44-a885-f0558c603b6e)

**Additional context**

**Comment by joshuahigginson1** [comment]
Does anyone have an update or hotfix on this issue?

**Comment by nagmesh** [comment]
Hello @alexhaycock , 

Thank you for your interest in LZA. Can you share SCPs and organizations-config used? So I can replicate this. 
In the cloudformation console log that you posted, can you check the gear icon for`Physical ID` and see if that Physical ID has changed. The only reason I can think that it would run a delete is if it see's a physical id change.

**Comment by alexhaycock** [comment]
Hi @nagmesh 

Apologies for the late response on this one. Is there a way I can send you the SCP's if still needed?

The physical ID looks to change as shown in the screenshot below.
![image](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/93584021/f4abdaa4-9633-493c-b5b3-dea615d815ba)

We believe that this is could possibly be down to us manually modifying the SCP statements we have in place in our dev LZA environments for quicker testing as its quicker than adding to the config and running the pipeline. This does mean that we have the following setting configured to allow us to do that:

`
scpRevertChangesConfig:
 enable: false
`

**Comment by nagmesh** [comment]
Thank you for the update @alexhaycock 

The previous version (older than 1.6.3) of the SCP removal via custom resource was based on the [policy name](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/release/v1.6.2/source/packages/%40aws-accelerator/constructs/lib/aws-organizations/create-policy/index.ts#L133). Policy names are unique in AWS Organizations. If the policy ID changed, it would clean up the older resource by looking up the name. However, because CloudFormation resources are created before being deleted, this led to a scenario where policy will not get applied.

In the latest (v1.7.0), cleanup process checks against the [policy ID](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/release/v1.7.0/source/packages/%40aws-accelerator/constructs/lib/aws-organizations/create-policy/index.ts#L91) before proceeding to delete any resources. This ensures that the correct resources are targeted for deletion, preventing the customer from being left without a policy during the cleanup process.

I will go ahead and close this issue. Please reopen it if you have any other questions on this matter.
