### ISSUE TITLE
Ability to push down cross-region and cross-account backups

### ISSUE THREAD

**Issue by snemir2** [awslabs/landing-zone-accelerator-on-aws#448]
In the example configurations, there are basic org-wide backup policies.    
Would be great if there was an example of cross-region and cross-account backup

**Comment by erwaxler** [comment]
Hi @snemir2 , thanks for reaching out to the Landing Zone Accelerator team. The Landing Zone Accelerator includes several sample configurations to demonstrate how the LZA can automate the provisioning of AWS resources in a variety of ways. Due to the enormous breadth and depth of AWS Services, we are unable to maintain examples for any given configuration. For cross-account and cross-region back-ups, I recommend consulting the [AWS Backup documentation](https://docs.aws.amazon.com/aws-backup/latest/devguide/manage-cross-account.html#create-organization) and using the LZA to implement an appropriate backup policy.

Thank you for your support of the Landing Zone Accelerator, please continue to raise issues to let us know how we can improve the solution!

**Comment by snemir2** [comment]
Thanks.   I am a bit surprised that cross-region backup is not a part of accelerator.    I would urge you to reconsider including an example (or perhaps maybe a documented feature) with the landing zone.
