### ISSUE TITLE
Global Tagging for cost 

### ISSUE THREAD

**Issue by frankscalzo** [awslabs/landing-zone-accelerator-on-aws#451]
maybe I  missed the section i am trying to see where the tag for  Accelerator | AWSAccelerator gets injected to every resource i would like to add to that since i have some global tags to set 

I  need to add tags to Lambda and rules and roles etc for cost purposes and right now i am editing each file to add the tag variable to them 

EX 

Lambda 
![Screenshot 2024-05-13 at 2 52 05 PM](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/10548647/94ddb9aa-0cbd-4c09-b208-966e1d3900d0)

Role
![Screenshot 2024-05-13 at 2 51 58 PM](https://github.com/awslabs/landing-zone-accelerator-on-aws/assets/10548647/4e6c88cc-e375-4096-a3c4-a7d64cc753ef)

**Comment by richardkeit** [comment]
Reference for an issue with Global tags - https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/415

**Comment by erwaxler** [comment]
Hi @frankscalzo , this feature is available in the LZA as of v1.5.0 you can find an example [here](https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/v1.6.0/classes/_aws_accelerator_config.GlobalConfig.html#tags). As @richardkeit alluded to in issue #415, some resources are not tagged due to differences in the backing API - I will keep that issue open to track the untagged resources. Since the requested behavior is available for use, I'll go ahead and close this issue. Thank you for supporting the Landing Zone Accelerator!

**Comment by andreprawira** [comment]
@erwaxler hi, i have a question, so in order to inject a tag to every resource deployed by lza, i need to add the tags in global-config.yaml right?

```tags:
  - key: lza
    value: training
```
