### ISSUE TITLE
Safe to delete stack AWSAccelerator-LoggingStack-XXX ?

### ISSUE THREAD

**Issue by jaristizabalc** [awslabs/landing-zone-accelerator-on-aws#488]
**Describe the bug**
I am stuck with the LZA Pipeline on an error state, on the Logging stage to be precise. It is on a stale state since after re-running the Pipeline it cannot be taken out of the DELETE_FAILED status. Is it safe to manually delete the stack and let the Pipeline re-create it?

**To Reproduce**
The problem started when changing the Tags settings on global-config.yaml, as the Pipeline complained that some resources could not be tagged due to a conflict with a SCP (default LZA guardrails), then we added an exception to allow the user running the Pipeline to bypass the SCP and tag all resources. The SCP is not a problem anymore, however, the Logging stack on the Log/Archive account is on a DELETE_FAILED status and cannot get it out of that.

- [ ] Version: 1.6

- [ ] Region: [us-east-1]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? Yes
- [ ] Were there any errors in the CloudWatch Logs?

**Comment by erwaxler** [comment]
Hi @jaristizabalc , thanks for reaching out to the Landing Zone Accelerator team. Deleting LZA stacks manually is not a recommended or safe operation. However since it appears in this case the stack was already attempted to be deleted resulting in the DELETE_FAILED state, you will need to continue deleting the stack entirely and cleaning up retained resources. After the stack has been successfully deleted, rerun the pipeline to attempt to recreate the stack.

Since this issue is describing the result of an SCP configuration rather than an issue in the LZA engine, I'll be closing this ticket. Please create a case with [AWS Support](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/contact-aws-support.html) if additional troubleshooting is required and they will be able to provide guidance more specific to your use case. Thank you for your support of the Landing Zone Accelerator!
