### ISSUE TITLE
Pushing updates via specific stages only

### ISSUE THREAD

**Issue by snemir2** [awslabs/landing-zone-accelerator-on-aws#489]
Is it possible to push targeted updates without a full pipeline run?
For example, to push out updates via customizations-config.yaml, most other steps would not have to run(I imagine) --- yet they do, and it is very time-consuming.

**Comment by erwaxler** [comment]
Hi @snemir2 , thanks for reaching out to the Landing Zone Accelerator team. Yes individual stages of the LZA can be run locally. This should be used with caution because as you mentioned, since there may be dependent resources in early stages depending on the resource to be deployed. I'd also draw your attention to this warning:

> Local use of the CLI should be used with caution. Configuration changes deployed via this method do not have an approval/diff gate by default. You can add an approval gate to deploy operations by appending the following option: --require-approval any-change

You can find instructions on running local `synth` and `deploy` commands on our Developer Guide page: https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/developer-guide/scripts/
