### ISSUE TITLE
LZA Pipeline Stuck on Finalize Stage Due to SCP Update Failure

### ISSUE THREAD

**Issue by adeolaolawuyi** [awslabs/landing-zone-accelerator-on-aws#513]
**Describe the bug**
The LZA pipeline deployment is encountering an issue where it gets stuck on the Finalize stage. The Finalize stack entered an "Update Failed" status due to the pipeline's inability to update Service Control Policies (SCPs). The SCP policy IDs referenced in the error messages do not match the policy IDs of the existing SCPs. The finalize stage appears to be trying to update policies that it cannot find. Despite attempting to roll back, the rollback process could not be completed without skipping SCP resources. After completing the rollback by skipping SCP resources, the stack status changed to "Update Rollback Complete." However, the issue persists even after retrying the stage and re-running the pipeline, preventing successful deployment completion.

**Note**: No changes were made to the SCP resources themselves during this process

**To Reproduce**
1. Start the LZA pipeline deployment.
2. The pipeline reaches the Finalize stage.
3. The stack status changes to "Update Failed" due to SCP update issues.
4. Attempt to roll back the stack.
5. Rollback cannot be completed without skipping SCP resources.
6. Complete the rollback by skipping SCP resources.
7. The stack status changes to "Update Rollback Complete."
8. Retry the Finalize stage.
9. Re-run the entire pipeline.

**Expected behavior**
The LZA pipeline should successfully complete all stages, including the Finalize stage, with SCPs updated as part of the stack deployment process.

**Please complete the following information about the solution:**

- [ ] Version: v.1.8.1
- [ ] Region: eu-west-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? Please see the screenshots.

**Screenshots**
![image](https://github.com/user-attachments/assets/78fca176-60a7-4339-a837-1bcd2bb4b20c)
![image (1)](https://github.com/user-attachments/assets/8e1a8c91-ea2c-4acd-bae2-a5ff89ad93a0)

**Additional context**

**Comment by bhkhatri221** [comment]
Hello @adeolaolawuyi, thank you for filing an issue with the Landing Zone Accelerator team! 

The issue you're facing could be due to the policy being deleted and recreated, which generated a different ID, causing the Finalize stack to become unsynchronized. A similar [issue ](https://github.com/awslabs/landing-zone-accelerator-on-aws/issues/441) has been reported before.

To better assist you with this issue, please provide the following information:
- Did this issue start during the upgrade process?
- What versions of the solution are you upgrading from and to?
- Were there any manual modifications of SCPs ?

Thanks, and we look forward to hearing back from you!

**Comment by adeolaolawuyi** [comment]
Hi @bhkhatri221, thank you for your response. 

Just to confirm the issue did not start during the LZA upgrade process.

The Accounts stack was failing to update and could not rollback. Then I tried to delete the stack, which could not delete because of the SCP resources, the SCP resources was skipped but it still ended up deleting the SCPs as part of the process. A rerun of the Accounts stage recreated the stack and the SCP resources again.

The current version we are using is v.1.8.1 and there was no manual modifications to SCPs.

**Comment by bhkhatri221** [comment]
Hello @adeolaolawuyi , thank you for additional information. 

LZA expects the policy to have been created in a previous execution. The solution creates a hash of the policy files and only create or update the policies if the policy has changed.  Since the policy hasn't changed, the custom resource that would create the policy is not being called in the accounts stack. To force the policy to be created or updated, you can add an environment variable to the CodeBuild project, which will force the custom resource to be executed. Here are the steps to create the environment variable:

- Navigate to CodeBuild and go to the Build projects.
- Find the project where the name ends in 'ToolkitProject'.
- Select the project and click on the 'Edit' button.
- Scroll down to the Environment section and expand the 'Additional configuration' section.
- The name of the variable will be 'ACCELERATOR_FORCED_UPDATE' set the value to 'true'.
- Scroll down and click on the 'Update project' button.

Once the environment variable has been added. release the LZA pipeline. After the pipeline has executed successfully the environment variable can be removed or set the value to 'false'. 

I hope this was helpful ! Let us know if this workaround works for you and if you have any further questions.

**Comment by adeolaolawuyi** [comment]
Hello @bhkhatri221 , thank you for response. The pipeline was able to complete successfully by following the workaround steps above. I also had no issues as well after removing the environmental variable and gave the pipeline a dry run. Thanks again for your assistance.
