### ISSUE TITLE
AWSAccelerator-LoggingStack Fails to Create Custom Resources/Gets Stuck Creating Custom Resources

### ISSUE THREAD

**Issue by turqual** [awslabs/landing-zone-accelerator-on-aws#540]
**Describe the bug**
In one of our accounts, the `AWSAccelerator-LoggingStack-<accountnumber>-eu-west-1` stack is getting stuck creating on some specific resources...
```
43/60 Currently in progress: 
  AWSAccelerator-LoggingStack-<accountnumber>-eu-west-1, 
  AcceleratorCentralLogBucketKeyLookup<string>, 
  LookupCentralSnsKeyArnParameter<string>, 
  S3PublicAccessBlock<string>, 
  LogsSubscriptionFilter<string>, 
  AutoScalingServiceLinkedRoleCreateServiceLinkedRoleResource<string>, 
  AWSServiceRoleForAWSCloud9CreateServiceLinkedRoleResource<string>
```

This happened after an SCP was applied directly to this specific account that blocked IAM permissions (`iam:create*` and `iam:AttachRolePolicy`) without an exception for the Accelerator Roles. We adjusted the SCP and reattempted the pipeline but were met with failures. We have tried removing the stack and related resources (S3 bucket, Lambda Functions, etc.) and having the pipeline recreate it but are still met with this issue. 

The CloudFormation stack simply hangs and does not return a 403 or any normal error code, just eventually times out after exactly an hour. Then if the stack is left to rollback, the rollback also takes an additional hour to eventually fail. The same is true for delete stack operations unless the troubled resources listed above are either manually removed or ignored from the stack delete command. 

**Expected behavior**
I would expect the stack to be able to be recreated without issue now that the permissions issue has been resolved within the account.

**Please complete the following information about the solution:**

- [x] Version: v1.9.1

> To get the version of the solution, you can look at the description of the created AWS CloudFormation stack used to install the LZA (AWSAccelerator-InstallerStack). For example, "__(SO0199) Landing Zone Accelerator on AWS. **Version 1.5.1.**__". If the description does not contain the version information, you can look at the Parameters of the stack for the **RepositoryBranchName** as that should contain the version number.

- [x] Region: eu-west-1
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**

**Additional context**
- We are using a separate Pipeline account from the main "central payer" through the `--context useExternalPipelineAccount=true` flag as documented in the implementation guide

**Comment by turqual** [comment]
Failed action from Cloudformation results in the following...
```

Logical ID: LookupCentralSnsKeyArnParameter<string>

Status Reason: CloudFormation did not receive a response from your Custom Resource. 
Please check your logs for requestId [68318.....b]. 
If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.
```

**Comment by gr-georgeshort** [comment]
Hi, 
Within LookupCentralSnsKeyArnParameter lambda function logs we see:

INFO	CREATE failed, responding with a marker physical resource id so that the subsequent DELETE will be ignored

{
  Status: 'FAILED',
  Reason: 'Error: Unsuccessful HTTP response: 403\n' +
    '    at ClientRequest.<anonymous> (/var/task/__entrypoint__.js:1:3076)\n' +
    '    at Object.onceWrapper (node:events:632:26)\n' +
    '    at ClientRequest.emit (node:events:517:28)\n' +
    '    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)\n' +
    '    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)\n' +
    '    at TLSSocket.socketOnData (node:_http_client:541:22)\n' +
    '    at TLSSocket.emit (node:events:517:28)\n' +
    '    at addChunk (node:internal/streams/readable:368:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:341:9)\n' +
    '    at Readable.push (node:internal/streams/readable:278:10)',
  StackId: 'arn:aws:cloudformation:eu-west-1:<account_id>:stack/AWSAccelerator-LoggingStack-<account_id>-eu-west-1/fa2e4720-*',
  RequestId: 'f15a83b3-*',
  PhysicalResourceId: 'AWSCDK::CustomResourceProviderFramework::CREATE_FAILED',
  LogicalResourceId: 'AcceleratorCentralLogBucketKeyLookup26F8C418',
  NoEcho: undefined,
  Data: undefined
}

This is after the success message being posted to https://cloudformation-custom-resource-response-euwest1.s3-eu-west-1.amazonaws.com when it has retrieved the kms key arn from the central logging account.

**Comment by erwaxler** [comment]
Hi @turqual , thanks for reaching out to the Landing Zone Accelerator team!

I've gone ahead and created an internal issue regarding the error handling in the `CustomResourceProviderFramework` Lambda function. For some additional background, the LZA uses a custom resource [construct](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/450807b2e458b5d3f042fccb2c2900d270d006a6/source/packages/%40aws-accelerator/constructs/lib/aws-ssm/ssm-parameter-lookup.ts#L60) to perform cross-account lookups to get data required for other stacks.

Based on the initial issue, I think what is most likely happening here is another SCP or restrictive control is blocking access to one of the actions performed by the custom resource which is causing it to fail. The fact that the error message is never raised and you need to wait for a timeout indicates an issue with the error handling of that function.

To diagnose this further in your environment, I would do the following:
1. Analyze SCPs for any statements that may be blocking the creation or retrieval of SSM Parameters by the role(s) attached to these functions, the functions likely exist in several accounts.
2. Take a closer look at the CloudWatch logs of the Lambda function that is failing during creation, that may give further context into where it is failing.
3. Check CloudTrail logs for failed actions in that account and region as this will clearly indicate what API operation is being denied. 

Please post any findings from the sources above and I'm happy to help try to narrow down a root cause. In the meantime, I'll keep this issue open to track error handling in that function.

**Comment by gr-georgeshort** [comment]
Hey @erwaxler, just checking you have seen my comment recently which shows the response of point 2 in yours.

**Comment by erwaxler** [comment]
Hey @gr-georgeshort thanks for pointing that out, I didn't realize those were from the Lambda logs. That doesn't seem like enough data to make a conclusion from unfortunately, in that case I would take a closer look at CloudTrail and the SCP definitions as those will be more fruitful.

**Comment by turqual** [comment]
I dug through and didn't see anything in the SCPs that would block this. 

Do you know what account(s) those SSM parameters it is looking for are in? I was thinking that I would check the KMS key policies within those accounts to see if there is a block there.

**Comment by erwaxler** [comment]
Thanks for taking a look. The LookupCentralSnsKeyArnParameter lookup is done from all accounts and assumes a role into the Log Archive account to retrieve the following parameter:

`/accelerator/kms/snstopic/key-arn`

It also appears that a more specific role is used for this lookup, assuming you aren't using a custom prefix check for usage of the role `AWSAccelerator-SnsTopic-KeyArnParam-Role` as that may be linked to the actions performed by the custom resource.

**Comment by turqual** [comment]
**_Side note:_** On the permissions front, for what it's worth, no other account within the org is having this issue currently.

**Comment by gr-georgeshort** [comment]
Am currently on a call with AWS Support. It looks like the initial issue could be with regard to the central log bucket key, here are the full logs from the lambda, we are not seeing anything useful in Cloudtrail.

2024-08-20T19:40:37.702Z	6e47b6ae-1b25-4fc5-af13-15b994169317	INFO	
{
    "RequestType": "Create",
    "ServiceToken": "arn:aws:lambda:eu-west-1:<account_id>:function:AWSAccelerator-LoggingSta-CustomSsmGetParameterVal-osQE6Ke9ZLXj",
    "ResponseURL": "...",
    "StackId": "arn:aws:cloudformation:eu-west-1:<account_id>:stack/AWSAccelerator-LoggingStack-<account_id>-eu-west-1/fa2e4720-5f1a-11ef-8c62-02e12ea43353",
    "RequestId": "f15a83b3-c918-4d1c-aa9f-19ffea581225",
    "LogicalResourceId": "AcceleratorCentralLogBucketKeyLookup26F8C418",
    "ResourceType": "Custom::SsmGetParameterValue",
    "ResourceProperties": {
        "ServiceToken": "arn:aws:lambda:eu-west-1:<account_id>:function:AWSAccelerator-LoggingSta-CustomSsmGetParameterVal-osQE6Ke9ZLXj",
        "invokingAccountID": "<account_id>",
        "assumeRoleArn": "arn:aws:iam::<log archive account id>:role/AWSAccelerator-eu-west-1-CentralBucket-KeyArnParam-Role",
        "parameterRegion": "eu-west-1",
        "parameterName": "/accelerator/logging/central-bucket/kms/arn",
        "invokingRegion": "eu-west-1",
        "parameterAccountID": "<log archive account id>",
        "uuid": "arn:aws:kms:eu-west-1:<log archive account id>:key/f14d3c9b-*"
    }
}

2024-08-20T19:40:38.366Z	6e47b6ae-1b25-4fc5-af13-15b994169317	INFO	Assuming role arn:aws:iam::<log archive account id>:role/AWSAccelerator-eu-west-1-CentralBucket-KeyArnParam-Role...

2024-08-20T19:40:38.608Z	6e47b6ae-1b25-4fc5-af13-15b994169317	INFO	submit response to cloudformation https://cloudformation-custom-resource-response-euwest1.s3-eu-west-1.amazonaws.com//arn%3Aaws%3Acloudformation%3Aeu-west-1%3A<account_id>%3Astack/AWSAccelerator-LoggingStack-<account_id>-eu-west-1/fa2e4720-5f1a-11ef-8c62-02e12ea43353%7CAcceleratorCentralLogBucketKeyLookup26F8C418%7Cf15a83b3-c918-4d1c-aa9f-19ffea581225?*** {
  Status: 'SUCCESS',
  Reason: 'SUCCESS',
  StackId: 'arn:aws:cloudformation:eu-west-1:<account_id>:stack/AWSAccelerator-LoggingStack-<account_id>-eu-west-1/fa2e4720-5f1a-11ef-8c62-02e12ea43353',
  RequestId: 'f15a83b3-c918-4d1c-aa9f-19ffea581225',
  PhysicalResourceId: 'arn:aws:kms:eu-west-1:<log archive account id>:key/f14d3c9b-*',
  LogicalResourceId: 'AcceleratorCentralLogBucketKeyLookup26F8C418',
  NoEcho: undefined,
  Data: undefined
}

2024-08-20T19:41:02.366Z	6e47b6ae-1b25-4fc5-af13-15b994169317	INFO	CREATE failed, responding with a marker physical resource id so that the subsequent DELETE will be ignored

2024-08-20T19:41:02.367Z	6e47b6ae-1b25-4fc5-af13-15b994169317	INFO	submit response to cloudformation https://cloudformation-custom-resource-response-euwest1.s3-eu-west-1.amazonaws.com//arn%3Aaws%3Acloudformation%3Aeu-west-1%3A<account_id>%3Astack/AWSAccelerator-LoggingStack-<account_id>-eu-west-1/fa2e4720-5f1a-11ef-8c62-02e12ea43353%7CAcceleratorCentralLogBucketKeyLookup26F8C418%7Cf15a83b3-c918-4d1c-aa9f-19ffea581225?*** {
  Status: 'FAILED',
  Reason: 'Error: Unsuccessful HTTP response: 403\n' +
    '    at ClientRequest.<anonymous> (/var/task/__entrypoint__.js:1:3076)\n' +
    '    at Object.onceWrapper (node:events:632:26)\n' +
    '    at ClientRequest.emit (node:events:517:28)\n' +
    '    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)\n' +
    '    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)\n' +
    '    at TLSSocket.socketOnData (node:_http_client:541:22)\n' +
    '    at TLSSocket.emit (node:events:517:28)\n' +
    '    at addChunk (node:internal/streams/readable:368:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:341:9)\n' +
    '    at Readable.push (node:internal/streams/readable:278:10)',
  StackId: 'arn:aws:cloudformation:eu-west-1:<account_id>:stack/AWSAccelerator-LoggingStack-<account_id>-eu-west-1/fa2e4720-5f1a-11ef-8c62-02e12ea43353',
  RequestId: 'f15a83b3-c918-4d1c-aa9f-19ffea581225',
  PhysicalResourceId: 'AWSCDK::CustomResourceProviderFramework::CREATE_FAILED',
  LogicalResourceId: 'AcceleratorCentralLogBucketKeyLookup26F8C418',
  NoEcho: undefined,
  Data: undefined
}

END RequestId: 6e47b6ae-1b25-4fc5-af13-15b994169317

**Comment by erwaxler** [comment]
This failing resource `AcceleratorCentralLogBucketKeyLookup26F8C418` appears to be different from the previous failure of `LookupCentralSnsKeyArnParameter` - these are both SSM lookups but for different values. The fact that multiple lookups are failing for different values makes me think this is a broader issue with all lookups being blocked, rather than a one-off.

Once retrieved, the KMS key is used to create an SNS Forwarder Lambda function - though that occurs outside the scope of this custom resource and I would expect to manifest in a different error.

To give more context on the code that is being executed here, this is the code executed for the `LookupCentralSnsKeyArnParameter` resource. The construct is created in the Logging stack here:

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/450807b2e458b5d3f042fccb2c2900d270d006a6/source/packages/%40aws-accelerator/accelerator/lib/stacks/logging-stack.ts#L2142

That creates the ssm-parameter-lookup construct:

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/450807b2e458b5d3f042fccb2c2900d270d006a6/source/packages/%40aws-accelerator/constructs/lib/aws-ssm/ssm-parameter-lookup.ts#L61

Which executes this code:

https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/450807b2e458b5d3f042fccb2c2900d270d006a6/source/packages/%40aws-accelerator/constructs/lib/aws-ssm/get-param-value/index.ts

The code only assumes a role and retrieves the parameter. The fact that two different lookups have failed similarly points to a single cause of failure for both issues.

Is it possible to temporarily remove the SCP from the account to verify if the issue is SCP-related or not?

**Comment by turqual** [comment]
Thanks for the support @erwaxler! Worked with AWS Support and troubleshooted through the applied SCPs. We had removed the  offending commands from the SCP initially and that did nothing, but removing the SCP from the account completely freed up the stack to be able to properly delete itself and re-provision without issue. 

Any idea why these actions would cause issues with SSM parameter Cross Account lookups?...
```
"Effect": "Deny",
"Action": [
  "ec2:CreateEgressOnlyInternetGateway",
  "ec2:CreateInternetGateway",
  "ec2:AttachInternetGateway",
  "elasticloadbalancing:CreateLoadBalancer",
  "ec2:CreateNetworkAcl*",
  "ec2:DeleteNetworkAcl*"
]...
```
