### ISSUE TITLE
Is there a "middle ground" for documentation between code reference and implementation guide?

### ISSUE THREAD

**Issue by roncanepa** [awslabs/landing-zone-accelerator-on-aws#84]
**Is your feature request related to a problem? Please describe.**
Hello!  I'm having a frustrating time building and further implementing our LZA.  We've just come off of an engagement with Proserv and while I understand how everything is put together (thanks to their help), I'm having a frustrating time anytime I try to implement something.  For example: now that v1.3.x supports permission sets in the LZA itself (thank you!), I want to implement them here.  But the [identitycenter code reference](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.IdentityCenterConfig.html) doesn't have much in the way of context since it's generated from code.

Meanwhile, the landing zone [implementation guide](https://aws.amazon.com/solutions/implementations/landing-zone-accelerator-on-aws/) is a great high-level reference but doesn't get down into the weeds enough to give me what I need.  

**Describe the feature you'd like**
I'm looking for a set of documentation that sits between the code reference and the implementation guide so that I don't have to puzzle out what I think/assume the config is supposed to be/mean.

**Additional context**
For instance, that identitycenter config I linked above doesn't explain what exactly `identityCenter1` is.  is that just a declaration to give the rest of the code/config something to hang off of and the name doesn't really matter?  Is that supposed to be "an identity center originally set up via LZA IAC"?  Ours was created manually since we first deployed with v1.2 so all our SSO config was done manually since it wasn't supported then.  If I were to add this identitycenter config into my LZA, is that going to wipe out my currently-configured SSO setup? Am I supposed to instead plug in details from my already-existing SSO Identify Center configuration?

Similarly, what is the customer-managed policy `ResourceConfigurationCollectorPolicy` that's referenced?  Is that something previously declared via a [PolicyConfig](https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.PolicyConfig.html) or something that already exists outside of the LZA (aka, created manually or whatever) in the example AWS environment?  Can the LZA do dependency ordering a la Helm in kubernetes land so that I can add a Policy via the LZA and then reference that policy in another LZA config file?

It's a frustrating experience trying to bounce between the class spec documentation to puzzle out what the intent of the developers was in order to figure out how I'm supposed to be building. I currently have tabs open for `IamConfig`, `IdentityCenterConfig`, `RoleSetConfig`, `PolicySetConfig`, and `PolicyConfig`, among others, in my attempt to put this together a simple permission set.  It's feeling like the LZA is really intended to be an internal product at this point. I've even been reading the LZA typescript code to try and gain a sense of expectations which feels like the opposite of what I should be doing.

Thank you for reading and the work that you're doing.

**Comment by awsclemj** [comment]
Hello @roncanepa and thank you for reaching out to the LZA team!

Your feedback on this matter is very much appreciated. We iterate on our documentation with each release, so this will help considerably as we scope additional content for our future releases.

To address your current question, I believe what you are requesting can be found in the [Administrator tasks](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/administrator-tasks.html) section of the Implementation Guide, as well as our public [Immersion Day](https://catalog.workshops.aws/landing-zone-accelerator/en-US). These guides are designed to be more of a walkthrough of certain configuration items with additional context rather than a strict API reference. 

I will call out that these guides are not exhaustive, and the configuration API reference is intended to be the source of truth for every feature/service that can be implemented in LZA. I think that some of your questions can be answered by making our property descriptions in the API reference clearer. That said, we will continue to add common administrative tasks to the walkthrough guides as the features become available. We'd also love to hear your feedback on these guides if they are not currently meeting your specific needs.

Thanks again, and we look forward to hearing back from you!

**Comment by awsclemj** [comment]
Hello @roncanepa,

Thanks again for your input on this matter. As of v1.4.0 of the solution, we have worked to overhaul our [README.md](https://github.com/awslabs/landing-zone-accelerator-on-aws/blob/main/README.md) as well as our config API documentation for `network-config`, `customizations-config`, and `security-config`. We have also added a new section for [Using the solution](https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/use-the-solution.html) in our Implementation Guide. We have backlog items to continue updating our API reference for other reference documents similarly as time allows in our forthcoming releases.

I believe our feedback loop is closed here and as such I will close the issue. Please feel free to re-open this issue or create a new issue if you find any additional documentation gaps going forward. Thank you for your support of the Landing Zone Accelerator!
